---

- name: Add crate repository.
  apt_repository:
    repo: 'ppa:crate/stable'
    state: present

- name: Install packages.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-software-properties
    - software-properties-common
    - crate
